version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db:/var/lib/mysql
     ports:
       - "3307:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8001:80"
     # restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./wp:/var/www/html

   phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        PMA_ARBITRARY: 1
        MYSQL_USER: wordpress
        MYSQL_PASSWORD: wordpress
        MYSQL_ROOT_PASSWORD: wordpress
      ports:
        - "8081:80"
      links:
        # for mysql container
        - "db:db"

volumes:
    db:
      driver: "local"
